#!/usr/bin/env bash

set -e

CONFIG="to_sync_files/install.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${BASEDIR}"
git pull --recurse-submodules && git submodule update
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -c "${CONFIG}" "${@}"

unameOut="$(uname -a)"
if [[ "$unameOut" =~ "MANJARO" ]]; then
    DISTRO="MANJARO"
elif [[ "$unameOut" =~ "Ubuntu" ]]; then
    DISTRO="UBUNTU"
elif [[ "$unameOut" =~ "Mac" ]]; then
    DISTRO="MAC"
else
    echo "Unsuported Linux distribution" && exit 1
fi

./scripts/install_dependency_manager.sh $DISTRO
./scripts/${DISTRO}/install_packages.sh
./scripts/${DISTRO}/tweak_configs.sh
./scripts/install_shell.sh
