#!/usr/bin/env bash

set -e

CONFIG="to_sync_files/install.conf.yaml"
SUBMODULE_DIRS=("dotbot" "asdf" "fzf" "powerlevel10k")
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${BASEDIR}"
for DIR in ${SUBMODULE_DIRS[@]}; do
    git -C "${DIR}" submodule sync --quiet --recursive || echo "Could not sync ${DIR} submodule"
    git submodule update --init --recursive "${DIR}" || echo "Could not update ${DIR} submodule"
done
git pull --recurse-submodules && git submodule update
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -c "${CONFIG}" "${@}"

unameOut="$(uname -a)"
if [[ "$unameOut" =~ "MANJARO" ]]; then
    DISTRO="MANJARO"
elif [[ "$unameOut" =~ "Ubuntu" ]]; then
    DISTRO="UBUNTU"
elif [[ "$unameOut" =~ "Mac" ]]; then
    DISTRO="MAC"
else
    echo "Unsuported Linux distribution" && exit 1
fi

./scripts/install_dependency_manager.sh $DISTRO
./scripts/${DISTRO}/install_packages.sh
./scripts/${DISTRO}/tweak_configs.sh
./scripts/install_shell.sh
