# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:${PATH}"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
# Bootstrap Homebrew from a known path. Run from $HOME so startup does not fail
# when the current working directory is not readable.
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(
    (cd "$HOME" && /opt/homebrew/bin/brew shellenv) 2>/dev/null
  )"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(
    (cd "$HOME" && /usr/local/bin/brew shellenv) 2>/dev/null
  )"
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

setopt APPEND_HISTORY
unsetopt SHARE_HISTORY
unsetopt INC_APPEND_HISTORY_TIME
unsetopt INC_APPEND_HISTORY

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git docker-compose asdf)

source $ZSH/oh-my-zsh.sh

# User configuration
# command completion
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
  autoload -Uz compinit
  compinit
fi
autoload -Uz compinit
compinit
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_TYPE=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='vim'
if [[ -n "$SSH_CONNECTION" ]]; then
  security show-keychain-info ~/Library/Keychains/login.keychain-db 2>/dev/null \
    || security unlock-keychain ~/Library/Keychains/login.keychain-db
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

. ~/.scripts/aliases.sh

# Jump
if command -v jump >/dev/null 2>&1; then
  eval "$(jump shell)"
fi

export PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/bin/chromium

export PIP_EXTRA_INDEX_URL=https://pypi.org/simple/
# Secrets (tokens, credentials) live in an untracked local file, not in this repo.
# See ~/.zsh_secrets.example for the expected format.
[ -f ~/.zsh_secrets ] && source ~/.zsh_secrets
export GPG_TTY=$(tty)

# Britecore
export AWS_DEFAULT_PROFILE=bcpro
export AWS_PROFILE=bcpro
export BRITECORE_CODE_DIR="${HOME}/Documents/computing/dev/projects/iws/BriteCore"
export BRITECORE_DATA_LOAD_DIR=~/bc-local-data-load
export KIND_EXPERIMENTAL_PROVIDER=podman

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
[ -s "${HOME}/.bun/_bun" ] && source "${HOME}/.bun/_bun"

# Created by `pipx` on 2025-01-07 18:48:01
export PATH="/Users/victorwjugow/.local/bin:$PATH"
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin/
export PATH=/opt/homebrew/Cellar/vim/9.1.1050/bin:$PATH

# Mysql
if command -v brew >/dev/null 2>&1; then
  export PKG_CONFIG_PATH="$(brew --prefix)/opt/mysql-client/lib/pkgconfig"
fi
export PATH="/opt/homebrew/opt/mysql-client@8.0/bin:$PATH"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"

# Others
export CLAUDE_CONFIG_DIR=/Users/victorwjugow/.claude/projects
